[package]
name = "hwlocality"
version = "1.0.0"
authors = ["Hadrien G. <knights_of_ni@gmx.com>", "Joseph Hirschfeld <j@ibj.io>", "Michael Nitschinger <michael@nitschinger.at>"]
license = "MIT"
keywords = ["hwloc"]
description = "Rust bindings for the hwloc hardware locality library"
repository = "https://github.com/HadrienG2/hwlocality"
documentation = "http://docs.rs/hwlocality/"
build = "build.rs"
links = "hwloc"
readme = "README.md"
edition = "2021"

[dependencies]
arrayvec = "0.7"
bitflags = "2.0"
derive_more = "0.99"
errno = "0.3"
libc = "0.2"
num_enum = "0.5"
once_cell = "1.17"
thiserror = "1.0"

[build-dependencies]
pkg-config = "0.3.8"

[dev-dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.45", features = ["Win32_Foundation", "Win32_System_Threading"] }
